[package]
name = "bessachet"
version = "0.1.0"
authors = ["Theo Barollet <theo.barollet@ensimag.fr>"]

[dependencies]
enum_primitive = "*"
array-init = "0.0.4"
lazy_static = "1.2.0"
stackvector = "1.0.2"
rand = "0.6.5"
